QuadEB/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("tom/", include("tom.urls")),
    path("admin/", admin.site.urls),
]

tom/urls.py
from django.urls import path

from . import views

app_name = "tom"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("target/<int:pk>/", views.TargetView, name="target"),
    path("observatory/<int:pk>/", views.ObservatoryView.as_view(), name="observatory"),
    path("person/<int:pk>/", views.PersonView.as_view(), name="person"),
    path("import_targets/", views.ImportTargetsView, name="import_targets"),
]

tom/models.py
from datetime import datetime
from astropy.coordinates import SkyCoord
from astropy.time import Time
import astropy.units as u
from django.db import models
from tom.generated_code.Tess_TICv8 import *
from tom.generated_code.Gaia_DR2 import *
from tom.generated_code.Gaia_DR3 import *


class Person(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    affiliation = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class TargetIdType(models.Model):
    id_type = models.CharField(max_length=100, unique=True)
    comment = models.CharField(max_length=200, blank=True)


class Target(models.Model):
    name = models.CharField(max_length=100, unique=True)
    type = models.CharField(max_length=100, default="")
    source = models.CharField(
        max_length=100, help_text="How target was identified/discovered", blank=True
    )
    # ra = models.FloatField(verbose_name="RA (deg)")
    # dec = models.FloatField(verbose_name="Dec (deg)")
    # pmra = models.FloatField(verbose_name="PM RA (mas/yr)", default=0)
    # pmdec = models.FloatField(verbose_name="PM Dec (mas/yr)", default=0)
    # distance = models.FloatField(verbose_name="Distance (pc)", default=0)
    # magnitude = models.FloatField()

    def __str__(self):
        return self.name.value

    # def coord(self) -> SkyCoord:
    #     return SkyCoord(
    #         ra=self.ra * u.deg,
    #         dec=self.dec * u.deg,
    #         pm_ra_cosdec=self.pmra * u.mas / u.yr,
    #         pm_dec=self.pmdec * u.mas / u.yr,
    #         frame="icrs",
    #     )

    # def isCloseTo(self, coord: SkyCoord, distance=10 * u.arcsec) -> bool:
    #     return coord.separation(self.coord()) < distance

    # def getByIdentifier(identifier_type: str, identifier: str):
    #     # target_identifier = TargetIdType.objects.get(id_type=identifier_type)
    #     # return Target.objects.get(...)
    #     pass  # TODO: finish this


class CatalogAssociation(models.Model):
    target = models.ForeignKey(Target, on_delete=models.CASCADE)
    catalog = models.CharField(max_length=100, help_text="Name of associated catalog")
    catalog_id = models.CharField(
        max_length=100, help_text="Identifier within associated catalog"
    )
    association = models.CharField(
        max_length=100, help_text="Reason for association with catalog object"
    )


class TargetIdentifier(models.Model):
    target = models.ForeignKey(Target, on_delete=models.CASCADE)
    id_type = models.ForeignKey(TargetIdType, on_delete=models.CASCADE)
    identifier = models.CharField(max_length=100)


class TargetList(models.Model):
    name = models.CharField(max_length=200, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=400)
    targets = models.ManyToManyField(Target)

    def __str__(self):
        return f"{self.name} (created {self.created:%Y-%m-%d %H:%M:%S} UTC)"


class Observatory(models.Model):
    nickname = models.CharField(max_length=15)
    name = models.CharField(max_length=100)
    iau_code = models.CharField(max_length=10)

    def __str__(self):
        return self.nickname


class ObservationPurpose(models.Model):
    purpose = models.CharField(max_length=100)

    def __str__(self):
        return self.purpose


class ObservingProgram(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def unknownProgram() -> str:
        return "Unknown"


class ObservingSession(models.Model):
    observingprogram = models.ForeignKey(ObservingProgram, on_delete=models.CASCADE)
    observatory = models.ForeignKey(Observatory, on_delete=models.CASCADE)
    utc_date = models.DateField()
    equipment = models.CharField(
        max_length=200,
        help_text=f"Format: <telescope>+<instrument>",
    )
    purpose = models.ForeignKey(ObservationPurpose, on_delete=models.CASCADE)
    observers = models.ManyToManyField(Person)

    def __str__(self):
        return f"{self.purpose} of {self.target} on {self.utc_date} @ {self.observatory.nickname} "

    def makeEquipmentString(telescope: str, instrument: str) -> str:
        return f"{telescope}+{instrument}"


class RawData(models.Model):
    target = models.ForeignKey(Target, on_delete=models.CASCADE)
    observingsession = models.ForeignKey(ObservingSession, on_delete=models.CASCADE)
    datetime_utc = models.DateTimeField(default=datetime.fromisoformat("1970-01-01"))
    uri = models.CharField(max_length=200)

    def __str__(self):
        return self.uri

    class Meta:
        abstract = True


class SpeckleRawData(RawData):
    gain = models.PositiveIntegerField(default=0)
    exposure_time_ms = models.PositiveIntegerField(default=0)
    channel = models.CharField(max_length=100)


class SpectrumRawData(RawData):
    fiber = models.CharField(max_length=20, default="")
    cross_disperser = models.CharField(max_length=100, default="")
    arm = models.CharField(max_length=30, default="")
    exposure_time = models.FloatField(default=0)


# class PhotometryRawData(RawData):
#     pass


# class OtherRawData(RawData):
#     description = models.CharField(max_length=200)


class ScienceResult(models.Model):
    target = models.ForeignKey(Target, on_delete=models.CASCADE)
    type = models.CharField(max_length=100)
    author = models.CharField(max_length=200, default="")
    uri = models.CharField(max_length=200)

    def __str__(self):
        return self.uri


class SpectrumEvaluation(ScienceResult):
    spectrum = models.ForeignKey(SpectrumRawData, on_delete=models.CASCADE)
    quality = models.FloatField(default=0, help_text="Scale of 5 with 5 highest")
    comment = models.CharField(max_length=200, default="")


class SpeckleResolution(ScienceResult):
    speckle = models.ForeignKey(SpeckleRawData, on_delete=models.CASCADE)
    coords = models.CharField(max_length=50, default="")
    filename = models.CharField(max_length=50, default="")
    epoch = models.FloatField(default=0)
    chi_sq = models.FloatField(default=0)
    seeing = models.FloatField(default=0)
    position_angle = models.FloatField(default=0)
    separation = models.FloatField(default=0)
    delta_mag = models.FloatField(default=0)
    filter = models.PositiveIntegerField(default=0)
    notes = models.CharField(max_length=100, default="")


class BinaryParameters(ScienceResult):
    system = models.CharField(max_length=50, help_text="Name of system, eg A, B, C")
    member = models.CharField(max_length=50, help_text="Name of component of system, eg a, b, c")
    period = models.FloatField(null=True, help_text="Period in days")
    t0 = models.FloatField(null=True, help_text="Date in BJD")
    duration = models.FloatField(null=True, help_text="Duration in hours")
    depth = models.FloatField(null=True)

tom/forms.py
from django import forms

class ImportTargetsForm(forms.Form):
    file = forms.FileField(max_length=10000, allow_empty_file=False, label="File of target IDs")
    require_all = forms.BooleanField(label="Fail if any IDs not found")

tom/views.py
from io import StringIO
import csv
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views import generic

from .models import *
from .forms import *
from .TargetImporter import *


class IndexView(generic.ListView):
    template_name = "tom/index.html"

    def get_queryset(self):
        return Target.objects.all()


def TargetView(request, pk):
    target = get_object_or_404(ScienceTarget, pk=pk)
    # observations = target.observation_set.all()
    # scienceresults = target.scienceresult_set.all()
    # specklerawdata = SpeckleRawData.objects.filter(
    #     observation__target__name=target.name
    # )
    context = {
        "target": target,
        # "observations": observations,
        # "specklerawdata": specklerawdata,
        # "scienceresults": scienceresults,
    }
    calibration_targets = target.calibrations
    if calibration_targets is not None:
        context["calibration_targets"] = calibration_targets.all()
    return render(request, "tom/target.html", context)


def ImportTargetsView(request):
    if request.method == "POST":
        form = ImportTargetsForm(request.POST, request.FILES)
        if form.is_valid():
            err_msg = TargetImporter.process_target_file(
                request.FILES["file"], form.cleaned_data["require_all"]
            )
            if err_msg == "":
                return HttpResponseRedirect("tom/import_targets_thanks")
            else:
                pass  # TODO: show error message to user
    else:
        form = ImportTargetsForm()
    return render(
        request,
        "tom/import_targets.html",
        {"form": form, "csv_columns": TargetImporter.csv_columns},
    )


class ObservatoryView(generic.DetailView):
    model = Observatory
    template_name = "tom/observatory.html"


class PersonView(generic.DetailView):
    model = Person
    template_name = "tom/person.html"

tom/templates/tom/import_targets.html
<form action="/tom/import_targets/" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

tom/templates/tom/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'tom/style.css' %}">

{% if target_list %}
Available Targets:
    <ul>
    {% for target in target_list %}
        <li><a href="{% url 'tom:target' target.id %}">{{ target.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No targets are available.</p>
{% endif %}

tom/templates/tom/observation.html
{% load static %}
<link rel="stylesheet" href="{% static 'tom/style.css' %}">

<title>{{ observation.target }} @ {{ observation.observatory }} on {{ observation.utc_date }}</title>
Observation ID = {{ observation.id }}<br>
Target = {{ observation.target }}<br>
Observatory = {{ observation.observatory }}<br>
UTC Date = {{ observation.utc_date }}<br>

{% if observation.observers.all %}
    <br><br>
    Observers ({{ observation.observers.all|length }})
    <ul>
        {% for observer in observation.observers.all %}
            <li>{{ observer.first_name }} {{ observer.last_name }}</li>
        {% endfor %}
    </ul>
{% endif %}

tom/templates/tom/observatory.html
<title>{{ observatory.name }}</title>
<b>{{ observatory.name }}</b><br>
IAU Code = {{ observatory.iau_code }}

tom/templates/tom/person.html
{% load static %}
<link rel="stylesheet" href="{% static 'tom/style.css' %}">

<h1>{% block title %}{{ person }} {% endblock %}</h1>
{% block content %}
<table>
    {% for field in person.items %}
        <tr>
            <td>{{ field }}</td>
        </tr>
    {% endfor %}
</table>
{% endblock %}

tom/templates/tom/target.html
{% load static %}
<link rel="stylesheet" href="{% static 'tom/style.css' %}">

<title>{{ target.name }}</title>

<body style="background-color:powderblue;">
<br>
<h1>{{ target.name }}</h1><br>
TIC ID = {{ target.tic_id }} <br>
GAIA ID = {{ target.gaia_id }} <br>
Magnitude = {{ target.magnitude }} <br>

{% if observations %}
    <h2>Observations ({{ observations|length }})</h2>
    <table>
        <tr><th>ID</th><th>Purpose</th><th>Site</th><th>Date</th></tr>
        {% for observation in observations %}
            <tr>
                <td><a href="{% url 'tom:observation' observation.id %}">{{ observation.id }}</a></td>
                <td>{{ observation.purpose }}</td>
                <td>{{ observation.observatory }}</td>
                <td>{{ observation.utc_date|date:"Y-m-d" }}</td>
            </tr>
        {% endfor %}
    </table>
{% endif %}

{% if specklerawdata %}
    <h2>Speckle Raw Data ({{ specklerawdata|length }})</h2>
    <table>
        <tr><th>URI</th><th>Gain</th><th>Exposure time</th><th>Num Sequences</th></tr>
        {% for rawdatum in specklerawdata %}
            <tr>
                <td>{{ rawdatum.uri }}</td>
                <td>{{ rawdatum.gain }}</td>
                <td>{{ rawdatum.exposure_time_ms }}</td>
                <td>{{ rawdatum.num_sequences }}</td>
            </tr>
        {% endfor %}
    </table>
{% endif %}

{% if scienceresults %}
    <h2>Science Results ({{ scienceresults|length }})</h2>
    <table>
        <tr><th>Type</th><th>URI</th></tr>
        {% for scienceresult in scienceresults %}
            <tr>
                <td>{{ scienceresult.type }}</td>
                <td>{{ scienceresult.uri }}</td>
            </tr>
        {% endfor %}
    </table>
{% endif %}

{% if calibration_targets %}
    <h2>Calibration Targets ({{ calibration_targets|length }})</h2>
    <table>
        <tr><th>Local ID</th></tr>
        {% for calibration_target in calibration_targets %}
            <tr>
                <td>{{ calibration_target }}</td>
            </tr>
        {% endfor %}
    </table>
{% endif %}


</body>